export const IROHA_DOMAIN_ID = 'atlas';
export const IROHA_ACCOUNT_SUFFIX = '@test';
export const IROHA_ADMIN_ACCOUNT = 'admin@test';
export const IROHA_PEER_ADDR = 'localhost:50051';
export const IROHA_ADMIN_PRIM_KEY = 'f101537e319568c765b2cc89698325604991dca57b9716b58016b253506cab70';


//Iroha constants for Batch Transactions
export const CMD_ADD_ASSET_QUANTITY = 'ADD_ASSET_QUANTITY';
export const CMD_ADD_SIGANTORY = 'ADD_SIGNATORY';
export const CMD_APPEND_ROLE = 'APPEND_ROLE';
export const CMD_COMPARE_AND_SET_ACCOUNT_DETAIL = 'COMPARE_AND_SET_ACCOUNT_DETAIL';
export const CMD_CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CMD_CREATE_ASSET = 'CREATE_ASSET';
export const CMD_CREATE_DOMAIN = 'CREATE_DOMAIN';
export const CMD_CREATE_ROLE = 'CREATE_ROLE';
export const CMD_DETACH_ROLE = 'DETACH_ROLE';
export const CMD_GRANT_PERMISSION = 'GRANT_PERMISSION';
export const CMD_REMOVE_PEER = 'REMOVE_PEER';
export const CMD_ADD_PEER = 'ADD_PEER';
export const CMD_REMOVE_SIGNATORY = 'REMOVE_SIGNATORY';
export const CMD_REVOKE_PERMISSION = 'REVOKE_PERMISSION';
export const CMD_SET_ACCOUNT_DETAIL = 'SET_ACCOUNT_DETAIL';
export const CMD_SET_ACCOUNT_QUORUM = 'SET_ACCOUNT_QUORUM';
export const CMD_SUB_ASSET_QUANTITY = 'SUB_ASSET_QUANTITY';
export const CMD_TRANSFER_ASSET_QUANTITY = 'TRANSFER_ASSET_QUANTITY';

export const QRY_GET_ACCOUNT = 'GET_ACCOUNT';
export const QRY_GET_BLOCK = 'GET_BLOCK';
export const QRY_GET_SIGNATORIES = 'GET_SIGNATORIES';
export const QRY_GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const QRY_GET_PENDING_TRANSACTIONS = 'GET_PENDING_TRANSACTIONS';
export const QRY_GET_ACCOUNT_TRANSACTIONS = 'GET_ACCOUNT_TRANSACTIONS';
export const QRY_GET_ACCOUNT_ASSET_TRANSACTIONS = 'GET_ACCOUNT_ASSET_TRANSACTIONS';
export const QRY_GET_ACCOUNT_ASSETS = 'GET_ACCOUNT_ASSETS';
export const QRY_GET_ACCOUNT_DETAIL = 'GET_ACCOUNT_DETAIL';
export const QRY_GET_ASSET_INFO = 'GET_ASSET_INFO';
export const QRY_GET_ROLES = 'GET_ROLES';
export const QRY_GET_ROLE_PERMS = 'GET_ROLE_PERMS';
export const QRY_GET_PEERS = 'GET_PEERS';
export const QRY_FETCH_COMMITS = 'GET_FETCH_COMMITS';


