export const IROHA_DOMAIN_ID = 'atlas';
export const IROHA_ACCOUNT_SUFFIX = '@test';
export const IROHA_ADMIN_ACCOUNT = 'admin@test';
export const IROHA_PEER_ADDR = 'localhost:50051';
export const IROHA_ADMIN_PRIM_KEY = 'f101537e319568c765b2cc89698325604991dca57b9716b58016b253506cab70';


//Iroha constants for Batch Transactions
export const CMD_ADD_ASSET_QUANTITY = 'ADD_ASSET_QUANTITY';
export const CMD_ADD_SIGANTORY = 'ADD_SIGNATORY';
export const CMD_APPEND_ROLE = 'APPEND_ROLE';
export const CMD_COMPARE_AND_SET_ACCOUNT_DETAIL = 'COMPARE_AND_SET_ACCOUNT_DETAIL';
export const CMD_CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const CMD_CREATE_ASSET = 'CREATE_ASSET';
export const CMD_CREATE_DOMAIN = 'CREATE_DOMAIN';
export const CMD_CREATE_ROLE = 'CREATE_ROLE';
export const CMD_DETACH_ROLE = 'DETACH_ROLE';
export const CMD_GRANT_PERMISSION = 'GRANT_PERMISSION';
export const CMD_REMOVE_PEER = 'REMOVE_PEER';
export const CMD_ADD_PEER = 'ADD_PEER';
export const CMD_REMOVE_SIGNATORY = 'REMOVE_SIGNATORY';
export const CMD_REVOKE_PERMISSION = 'REVOKE_PERMISSION';
export const CMD_SET_ACCOUNT_DETAIL = 'SET_ACCOUNT_DETAIL';
export const CMD_SET_ACCOUNT_QUORUM = 'SET_ACCOUNT_QUORUM';
export const CMD_SUB_ASSET_QUANTITY = 'SUB_ASSET_QUANTITY';
export const CMD_TRANSFER_ASSET_QUANTITY = 'TRANSFER_ASSET_QUANTITY';

